% fs3t3.m
function Hd = fs3t3
%FS3T3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 02-Apr-2020 13:55:44

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 460;  % Sampling Frequency

Fstop1 = 123;             % First Stopband Frequency
Fpass1 = 125;             % First Passband Frequency
Fpass2 = 133;             % Second Passband Frequency
Fstop2 = 135;             % Second Stopband Frequency
Dstop1 = 0.0001;          % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 1e-05;           % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
